# Generated by Django 5.0.1 on 2024-02-10 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_deadline',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
