# Generated by Django 5.0.1 on 2024-02-10 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMApp', '0002_task_task_deadline_alter_expense_expense_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_end',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_deadline',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_notes',
            field=models.TextField(blank=True),
        ),
    ]
