# Generated by Django 5.0.1 on 2024-02-10 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMApp', '0004_alter_project_project_end_alter_task_task_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_deadline',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
