# Generated by Django 5.0.1 on 2024-02-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMApp', '0006_rename_expense_description_expense_expense_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense_amount',
            new_name='expense_amt',
        ),
    ]
