# Generated by Django 5.0.1 on 2024-02-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMApp', '0007_rename_expense_amount_expense_expense_amt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualtaskassignment',
            old_name='task_assignment_id',
            new_name='assignment_id',
        ),
    ]
