# Generated by Django 5.0.1 on 2024-02-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMApp', '0008_rename_task_assignment_id_individualtaskassignment_assignment_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndividualTaskAssignment',
            new_name='TaskAssignment',
        ),
    ]
