# Generated by Django 5.0.1 on 2024-02-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMApp', '0011_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_text',
            field=models.CharField(max_length=255),
        ),
    ]
