# Generated by Django 5.0.1 on 2024-03-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMApp', '0012_alter_notification_notif_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.IntegerField(choices=[(0, 'Ongoing'), (1, 'Finished'), (2, 'Archived')], default=0),
        ),
    ]
