# Generated by Django 5.0.1 on 2024-03-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMApp', '0013_alter_project_project_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='taskassignment',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='taskassignment',
            old_name='task_id',
            new_name='task',
        ),
    ]
