# Generated by Django 5.0.1 on 2024-05-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMApp', '0014_rename_member_id_expense_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.BinaryField(),
        ),
    ]
