# Generated by Django 5.0.1 on 2024-05-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMApp', '0015_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.IntegerField(choices=[(0, 'In Progress'), (1, 'For Review'), (2, 'Completed')], default=0),
        ),
    ]
